In [1]:
import os
import pandas as pd

root = '/workspace/data/도서대출자료'
month = '1월'
book_file_name = '부산광역시 강서도서관 장서 대출목록 (2024년 01월).xlsx'

df_book = pd.read_excel(os.path.join(root, month, book_file_name))
df_book = df_book.loc[:, ['도서명', '저자', '출판사', '권', '도서권수', '대출건수', 'ISBN', '등록일자']]
display(df_book)

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,도서명,저자,출판사,권,도서권수,대출건수,ISBN,등록일자
0,파리,이양훈 글;정유진 그림,성림북스,NaN,1,0,9791188762651,2024-01-31
1,태극기를 올려라!,최미소 지음;이수영 그림,키큰도토리,NaN,1,0,9791192762029,2024-01-31
2,(이희수 선생님이 들려주는)이슬람 제대로 알기,이희수 지음,노란돼지,NaN,1,0,9791197441004,2024-01-31
3,"임진왜란, 일본을 무찌른 조선의 장군들",박은정 지음;토끼도둑 그림,휴먼어린이,NaN,1,0,9788965915133,2024-01-31
4,"조선 건국, 나라의 운명을 바꾼 리더들",고수산나 글;이광익 그림,휴먼어린이,NaN,1,0,9788965915072,2024-01-31
...,...,...,...,...,...,...,...,...
148005,고삐 풀린 영어,류성완;손정민;조영민 공저,프로방스,NaN,1,0,9788989239246,2004-07-08
148006,인류사를 이끈 운명의 순간들:재구성한 역사적 사건 12편,슈테판 츠바이크 원작;이관우 옮김,공주대학교 출판부,NaN,1,0,9788988421437,2004-07-08
148007,언어의 다양한 풍경=:,랑카 비엘작;룰랑 브르통 지음;신광순 옮김,시공사,117,1,0,9788952736048,2004-07-08
148008,사진=:빛과 그림자의 예술,캉탱 바작 지음;송기형 옮김,시공사,118,1,0,9788952736482,2004-07-08
148009,송영과 떠나는 음악여행,송영 지음,窓,NaN,1,1,9788974530631,1970-01-01

## 데이터 결측치 개수

In [2]:
df_book.isnull().sum()

도서명          0
저자         108
출판사       2117
권       109373
도서권수         0
대출건수         0
ISBN         0
등록일자         0
dtype: int64