In [1]:
import os
import pandas as pd

root = '/workspace/data/도서대출자료'
month = '1월'
book_file_name = '부산광역시 부산진구어린이청소년도서관 장서 대출목록 (2024년 01월).xlsx'

df_book = pd.read_excel(os.path.join(root, month, book_file_name))
df_book = df_book.loc[:, ['도서명', '저자', '출판사', '권', '도서권수', '대출건수', 'ISBN', '등록일자']]
display(df_book)

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,도서명,저자,출판사,권,도서권수,대출건수,ISBN,등록일자
0,나의 뉴욕 수업:호퍼의 도시에서 나를 발견하다,곽아람 지음,아트북스,NaN,1,2,9788961964333,2024-01-23
1,왕과 사자,김주현 글;이로우 그림,만만한책방,NaN,1,1,9791189499617,2024-01-23
2,기이한 추적:아컴호러 소설,"제니퍼 브로젝,리처드 리 바이어스,아만다 다우넘 외 지음;홍지로 옮김",아스모디코리아,NaN,1,2,9791197826443,2024-01-23
3,나만 옳다는 착각,크리스토퍼 J. 퍼거슨 지음;김희봉 옮김,선순환,NaN,1,1,9791197578038,2024-01-23
4,고독한 밤에 호루라기를 불어라:이응준 산문집,이응준 지음,민음사,NaN,1,1,9788937426162,2024-01-23
...,...,...,...,...,...,...,...,...
71888,지구의 노래:생태주의 세계관이 찾은 새로운 과학 문명 패러다임,스테판 하딩 지음;박혜숙 옮김,현암사,NaN,1,0,9788932315928,2015-12-09
71889,"내가 사랑한 지구:판구조론, 지질학자들이 밝혀낸 지구의 움직임",최덕근 지음,휴머니스트,NaN,1,4,9788958627975,2015-12-09
71890,"(처음 읽는)지구의 역사:별똥별 아줌마, 불덩이 지구를 누비다",이지유 지음,휴머니스트,NaN,1,9,9788958626442,2015-12-09
71891,오늘의 지구를 말씀 드리겠습니다:과학으로 읽는 지구 설명서,김추령 지음,양철북출판사,NaN,1,3,9788963720623,2015-12-09
71892,경도 이야기:인류 최초로 바다의 시공간을 밝혀낸 도전의 역사,데이바 소벨 지음;김진준 옮김,웅진씽크빅,NaN,1,1,9788901152394,2015-12-09

## 데이터 결측치 개수

In [2]:
df_book.isnull().sum()

도서명         0
저자          3
출판사      1086
권       45657
도서권수        0
대출건수        0
ISBN        0
등록일자        0
dtype: int64