In [1]:
import os
import pandas as pd

root = '/workspace/data/도서대출자료'
month = '1월'
book_file_name = '부산광역시립구포도서관 장서 대출목록 (2024년 01월).xlsx'

df_book = pd.read_excel(os.path.join(root, month, book_file_name))
df_book = df_book.loc[:, ['도서명', '저자', '출판사', '권', '도서권수', '대출건수', 'ISBN', '등록일자']]
display(df_book)

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,도서명,저자,출판사,권,도서권수,대출건수,ISBN,등록일자
0,지구의 온도가 1℃ 오르면 어떻게 되나요,이두현 외,푸른길,NaN,1,0,9788962910223,2024-01-28
1,해녀들,채헌,네오북스,NaN,1,0,9791157403721,2024-01-28
2,푸른 바다의 상괭이,민준영,춘희네책방,NaN,1,0,9791193277003,2024-01-28
3,지구의 온도가 1℃ 오르면 어떻게 되나요,이두현 외,푸른길,NaN,1,0,9788962910223,2024-01-28
4,푸른 바다의 상괭이,민준영,춘희네책방,NaN,1,0,9791193277003,2024-01-28
...,...,...,...,...,...,...,...,...
402289,나도 컴퓨터를 잘했으면 좋겠다,정순영,나노북스,NaN,1,0,9788989526131,2004-06-19
402290,나도 컴퓨터를 잘했으면 좋겠다,이수안,나노북스,NaN,1,0,9788989526124,2004-06-19
402291,나도 컴퓨터를 잘했으면 좋겠다,이원종,나노북스,NaN,1,0,9788989526117,2004-06-19
402292,식탁 옥수수,김창홍 저,멀티북스,NaN,2,0,9788991041028,2004-06-19
402293,(유쾌한) 엑셀 교과서,곽승주 저,제우미디어,1,1,0,9788990886859,2004-06-19

## 데이터 결측치 개수

In [2]:
df_book.isnull().sum()

도서명          0
저자          83
출판사       6128
권       321426
도서권수         0
대출건수         0
ISBN         0
등록일자         0
dtype: int64