In [1]:
import os
import pandas as pd

root = '/workspace/data/도서대출자료'
month = '1월'
book_file_name = '부산광역시립부전도서관 장서 대출목록 (2024년 01월).xlsx'

df_book = pd.read_excel(os.path.join(root, month, book_file_name))
df_book = df_book.loc[:, ['도서명', '저자', '출판사', '권', '도서권수', '대출건수', 'ISBN', '등록일자']]
display(df_book)

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,도서명,저자,출판사,권,도서권수,대출건수,ISBN,등록일자
0,훌훌:문경민 장편소설,문경민 지음,문학동네,NaN,1,0,9788954685030,2022-08-03
1,여름 방학 숙제 조작단:이진하 장편동화,이진하 지음;정진희 그림,사계절(사계절출판사),NaN,1,0,9791160947441,2022-08-03
2,알고 보면 반할 지도:박물관 큐레이터가 들려주는 신비로운 고지도 이야기,정대영 지음,태학사,NaN,1,0,9791168100336,2022-08-03
3,감 매거진,감씨편집팀;나르실리온 사진,에잇애플,14,1,0,9791189485115,2022-07-25
4,(역사 무식자도 쉽게 맥을 잡는)단박에 한국사,심용환 지음;방상호 그림,위즈덤하우스,NaN,1,0,9791162201435,2022-07-25
...,...,...,...,...,...,...,...,...
333387,영어의 기초를 잡아주는 3 STEP 초등영어,임기화,매일경제신문사,NaN,1,0,9788974422288,2004-06-12
333388,주식투자의 원칙,이은기,청림출판,NaN,1,0,9788935204892,2004-06-12
333389,나의 두 번째 주식투자,김대욱,국일증권경제연구소,NaN,1,0,9788957820315,2004-06-12
333390,세상을 바꾸는 돈의 사용법,야마모토 료이치,미래의창,NaN,1,0,9788959890026,2004-06-12
333391,(통합) 韓國史,정재준 편저,고시동네,NaN,1,0,9788960250352,2004-06-12

## 데이터 결측치 개수

In [2]:
df_book.isnull().sum()

도서명          2
저자         115
출판사       3575
권       288819
도서권수         0
대출건수         0
ISBN         0
등록일자         0
dtype: int64