In [1]:
import os
import pandas as pd

root = '/workspace/data/도서대출자료'
month = '1월'
book_file_name = '부산광역시 만덕도서관 장서 대출목록 (2024년 01월).xlsx'

df_book = pd.read_excel(os.path.join(root, month, book_file_name))
df_book = df_book.loc[:, ['도서명', '저자', '출판사', '권', '도서권수', '대출건수', 'ISBN', '등록일자']]
display(df_book)

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,도서명,저자,출판사,권,도서권수,대출건수,ISBN,등록일자
0,보통 이하의 것들,조르주 페렉 지음;김호영 옮김,녹색광선,NaN,1,2,9791198375315,2024-01-25
1,신들의 양식은 어떻게 세상에 왔나,허버트 조지 웰스 지음;박아람 옮김,휴머니스트,NaN,1,2,9791170870876,2024-01-25
2,우리 오늘도 살아 있네?,긍씨 글.그림,위즈덤하우스,NaN,1,4,9791171710904,2024-01-25
3,나는 쇼피로 통했다:처음 시작하는 해외 셀러,스테비(이영주) 지음,북샾일공칠(book#107),NaN,1,2,9791188033126,2024-01-25
4,HIIT의 과학,잉그리드 클레이 지음;이민아 옮김,사이언스북스,NaN,1,2,9791192908045,2024-01-25
...,...,...,...,...,...,...,...,...
166229,마법 천자문,시리얼,북21아울북,1,2,66,9788950906047,2004-07-13
166230,(소설)선,문화영,수선재,3,2,12,9788989150169,2004-07-13
166231,(소설)선,문화영,수선재,2,2,12,9788989150152,2004-07-13
166232,(소설)선,문화영,수선재,1,2,18,9788989150145,2004-07-13
166233,(노벨 평화상에서 통일까지)김대중,장세현 글;윤미덕 그림,파란자전거,NaN,2,3,9788989192022,2004-07-13

## 데이터 결측치 개수

In [2]:
df_book.isnull().sum()

도서명          0
저자         313
출판사       2293
권       131102
도서권수         0
대출건수         0
ISBN         0
등록일자         0
dtype: int64