In [1]:
import os
import pandas as pd

root = '/workspace/data/도서대출자료'
month = '1월'
book_file_name = '부산광역시 남구도서관 장서 대출목록 (2024년 01월).xlsx'

df_book = pd.read_excel(os.path.join(root, month, book_file_name))
df_book = df_book.loc[:, ['도서명', '저자', '출판사', '권', '도서권수', '대출건수', 'ISBN', '등록일자']]
display(df_book)

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,도서명,저자,출판사,권,도서권수,대출건수,ISBN,등록일자
0,길 안내를 시작합니다!,최옥임 글;배종숙 그림,교원,NaN,1,0,9788921482891,2024-01-30
1,투투네 대장간,김경희 글;송은경 그림,교원,NaN,1,0,9788921482884,2024-01-30
2,쓰레기꽃이 피었습니다!,유계영 글;안상선 그림,교원,NaN,1,0,9788921482907,2024-01-30
3,물 도깨비 나라 숲 도깨비 나라,양승현 글;허지나 그림,교원,NaN,1,0,9788921482877,2024-01-30
4,농촌 쥐와 공장 쥐,이혜다 글;전인숙 그림,교원,NaN,1,0,9788921482860,2024-01-30
...,...,...,...,...,...,...,...,...
261933,영산쇠머리대기[DVD],국립문화재연구소,국립문화재연구소,4,1,0,9788981243180,2004-02-17
261934,영산쇠머리대기[DVD],국립문화재연구소,국립문화재연구소,3,1,0,9788981243104,2004-02-17
261935,영산쇠머리대기[DVD],국립문화재연구소,국립문화재연구소,2,1,0,9788981243166,2004-02-17
261936,영산쇠머리대기[DVD],국립문화재연구소,국립문화재연구소,1,1,0,9788981243098,2004-02-17
261937,파퓰러 피아노 명곡집=Popular piano repertory,편집부,음악세계,1,1,0,9788981051099,2004-02-17

## 데이터 결측치 개수

In [2]:
df_book.isnull().sum()

도서명          3
저자         180
출판사       5564
권       191802
도서권수         0
대출건수         0
ISBN         0
등록일자         0
dtype: int64