## 데이터

In [3]:
import os
import pandas as pd

root = '/workspace/data/도서대출자료'
month = '1월'
book_file_name = '부산광역시 강서기적의도서관 장서 대출목록 (2024년 01월).xlsx'

df_book = pd.read_excel(os.path.join(root, month, book_file_name))
df_book = df_book.loc[:, ['도서명', '저자', '출판사', '권', '도서권수', '대출건수', 'ISBN', '등록일자']]
display(df_book)

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,도서명,저자,출판사,권,도서권수,대출건수,ISBN,등록일자
0,토지:박경리 대하소설.,박경리 지음,다산책방,7,1,0,9791130699530,2024-01-23
1,토지:박경리 대하소설.,박경리 지음,다산책방,9,1,0,9791130699554,2024-01-23
2,토지:박경리 대하소설.,박경리 지음,다산책방,8,1,0,9791130699547,2024-01-23
3,토지:박경리 대하소설.,박경리 지음,다산책방,6,1,0,9791130699523,2024-01-23
4,토지:박경리 대하소설.,박경리 지음,다산책방,5,1,0,9791130699516,2024-01-23
...,...,...,...,...,...,...,...,...
71855,"#너에게:너에게 보내는 편지, 완글",하태완 지음,넥서스,NaN,1,17,9788998454654,2018-07-08
71856,"#걸보스:훔친 책을 팔던 소녀, 5년 만에 1000억대 CEO가 되다",소피아 아모루소 지음;노지양 옮김,이봄,NaN,1,10,9791186195321,2018-07-08
71857,1026:김진명 장편소설,김진명 지음,새움출판사,NaN,1,56,9788993964141,2018-07-08
71858,28:정유정 장편소설,정유정 지음,은행나무,NaN,1,85,9788956607030,2018-07-08
71859,13.67:찬호께이 장편소설,찬호께이 지음;강초아 옮김,한스미디어,NaN,1,22,9788959758340,2018-07-08

## 데이터 결측치 개수

In [4]:
df_book.isnull().sum()

도서명         0
저자          0
출판사      2347
권       55404
도서권수        0
대출건수        0
ISBN        0
등록일자        0
dtype: int64