In [1]:
import os
import pandas as pd

root = '/workspace/data/도서대출자료'
month = '1월'
book_file_name = '부산광역시 재송어린이도서관 장서 대출목록 (2024년 01월).xlsx'

df_book = pd.read_excel(os.path.join(root, month, book_file_name))
df_book = df_book.loc[:, ['도서명', '저자', '출판사', '권', '도서권수', '대출건수', 'ISBN', '등록일자']]
display(df_book)

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,도서명,저자,출판사,권,도서권수,대출건수,ISBN,등록일자
0,쓰레기용,백은하 글;김유강 그림,파랑새,NaN,1,0,9788961550642,2024-01-24
1,폭발물 처리반이 조우한 스핀,사토 기와무 지음;김은모 옮김,블루홀식스(블루홀6),NaN,1,1,9791193149089,2024-01-24
2,철학자의 걷기 수업,알베르트 키츨러 지음;유영미 옮김,푸른숲,NaN,1,0,9791156754145,2024-01-24
3,(내 안의 충동에서 자유로워지는) 절제 수업,라이언 홀리데이 지음;정지인 옮김,다산초당,NaN,1,1,9791130649207,2024-01-24
4,(류승재 특급 비법) 진짜 수학 공부법,류승재 지음,경향BP(경향비피),NaN,1,1,9788969525307,2024-01-24
...,...,...,...,...,...,...,...,...
144882,봄날,김종혁 감독,이엔이미디어,1,1,0,8809036442110,2006-05-23
144883,신부와 편견,거린더 차다 감독,스타맥스,NaN,1,0,8809032222884,2006-05-23
144884,연인,장이모 감독,NaN,NaN,1,0,9789032222703,2006-05-23
144885,네버랜드를 찾아서,마크 포스터 감독,NaN,NaN,1,0,8801834512576,2006-05-23
144886,반지의 제왕:왕의 귀환,피터 잭슨 감독,문학동네,NaN,2,0,9788982819292,2006-05-23

## 데이터 결측치 개수

In [2]:
df_book.isnull().sum()

도서명         0
저자         18
출판사      4424
권       79557
도서권수        0
대출건수        0
ISBN        0
등록일자        0
dtype: int64