In [5]:
import os
import pandas as pd

root = '/workspace/data/도서대출자료'
month = '1월'
book_file_name = '부산광역시립해운대도서관 장서 대출목록 (2024년 01월).xlsx'

df_book = pd.read_excel(os.path.join(root, month, book_file_name))
df_book = df_book.loc[:, ['도서명', '저자', '출판사', '권', '도서권수', '대출건수', 'ISBN', '등록일자']]
display(df_book)

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,도서명,저자,출판사,권,도서권수,대출건수,ISBN,등록일자
0,내일은 실험왕:시즌 2.,스토리 a. 글;홍종현 그림,미래엔,7,1,0,9791168416338,2024-01-24
1,천하무적 개냥이 수사대:시즌 2.,이승민 글;윤태규 그림,위즈덤하우스,2,1,0,9791171710096,2024-01-24
2,Turtle in paradise,Jennifer L. Holm;illustrated by Savanna Ganucheau,Random House Graphic,NaN,1,0,9780593126301,2024-01-24
3,Bad Kitty gets a phone,Nick Bruel,Roaring Brook Press,NaN,1,0,9781250749963,2024-01-24
4,Bad Kitty goes on vacation,Nick Bruel,Roaring Brook Press,NaN,1,0,9781250208088,2024-01-24
...,...,...,...,...,...,...,...,...
351401,사람의 아들=:,이문열 지음,민음사,NaN,1,0,9788937480485,2004-09-12
351402,행복을 파는 난쟁이=:,안하림 지음,은행나무,NaN,1,0,9788956600857,2004-09-12
351403,문학시간에 소설읽기=:,전국국어교사모임 엮음,나라말,2,1,0,9788987402376,2004-09-12
351404,문학시간에 소설읽기=:,전국국어교사모임 엮음,나라말,1,1,0,9788987402369,2004-09-12
351405,문학시간에 시읽기=:,전국국어교사모임 엮음,나라말,1,1,0,9788987402390,2004-09-12

## 데이터 결측치 개수

In [6]:
df_book.isnull().sum()

도서명          2
저자          58
출판사      10326
권       284644
도서권수         0
대출건수         0
ISBN         0
등록일자         0
dtype: int64