In [1]:
import os
import pandas as pd

root = '/workspace/data/도서대출자료'
month = '1월'
book_file_name = '부산광역시 반여도서관 장서 대출목록 (2024년 01월).xlsx'

df_book = pd.read_excel(os.path.join(root, month, book_file_name))
df_book = df_book.loc[:, ['도서명', '저자', '출판사', '권', '도서권수', '대출건수', 'ISBN', '등록일자']]
display(df_book)

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,도서명,저자,출판사,권,도서권수,대출건수,ISBN,등록일자
0,후기스콜라 철학과 르네상스 철학,"프레드릭 코플스턴 저;이남원,정용수 [공]역",북코리아,NaN,1,1,9788963247656,2024-01-24
1,위너.,프레드릭 배크만 지음;이은선 옮김,다산책방,2,1,1,9791130649184,2024-01-24
2,소설 보다:겨울 2023,김기태 [공]지음,문학과지성사,NaN,1,0,9788932042343,2024-01-24
3,세상 끝의 살인,아라키 아카네 지음;이규원 옮김,북스피어,NaN,1,1,9791192313450,2024-01-24
4,그런 일은 없어요,나데즈다 테피 지음;강수경 옮김,지만지드라마,NaN,1,0,9791128867453,2024-01-24
...,...,...,...,...,...,...,...,...
106021,한국 고전 여성문학의 세계,이혜순;정하영 공편,이화여자대학교출판부,NaN,1,0,9788973003402,2004-05-27
106022,百濟史硏究論著總攬,呂弘基;白種伍;金炳熙 共著,서경문화사,NaN,1,0,9788986931556,2004-05-27
106023,고도 상수처리,이성우...[외]저,東和技術,NaN,1,0,9788942502219,2004-05-27
106024,병원경영학,병원전략경영개발원 편저,신광출판사,NaN,1,0,9788970696461,2004-05-27
106025,사회복지 경제학 연구,지은구 저,청목출판사,NaN,1,0,9788955650433,2004-05-27

## 데이터 결측치 개수

In [2]:
df_book.isnull().sum()

도서명         1
저자         74
출판사      1660
권       83645
도서권수        0
대출건수        0
ISBN        0
등록일자        0
dtype: int64